export interface DefaultSource {
  type: string;
  title: string;
  url: string;
  category: string;
  language: string;
  imageUrl?: string;
  id?: string;
}

export const DEAD_SOURCE_URLS = new Set<string>([
  "https://www.bloggerwissen.de/feed/",
  "https://mindsandmarkets.de/feed/",
  "https://www.bitsundso.de/feed/m4a/",
  "https://www.deutschlandfunk.de/der-tag-104.xml"
]);

export const DEFAULT_SOURCES: DefaultSource[] = [
  // ==========================================
  // PODCASTS (Deutsch)
  // ==========================================
  { type: 'podcasts', title: '11KM: der tagesschau-Podcast', url: 'https://www.ndr.de/nachrichten/info/podcast5518.xml', category: 'Nachrichten', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts221/v4/da/cd/3c/dacd3c03-20e7-e0a2-db59-c80bb013fce6/mza_13975641150493506875.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Lage der Nation', url: 'https://feeds.lagedernation.org/feeds/ldn-mp3.xml', category: 'Politik', language: 'de', imageUrl: 'https://lagedernation.org/wp-content/blogs.dir/10/files/2020/06/apple_podcast_artwork_reverse.png' },
  { type: 'podcasts', title: 'Zeit Verbrechen', url: 'https://zeitverlag.podigee.io/feed/mp3', category: 'True Crime', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/be/22/24/be2224ef-7d33-ad2a-a466-0cad62b4dcd3/mza_1379870103000080830.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Quarks - Wissenschaft und mehr', url: 'https://www1.wdr.de/radio/podcasts/wdr5/quarks-116.podcast', category: 'Wissen', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/80/df/0a/80df0a42-7cf2-7634-1875-103a83015a9f/mza_17316047715694762886.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'SWR2 Wissen', url: 'https://www.swr.de/~podcast/swr2/wissen/podcast-swr2-wissen-100.xml', category: 'Wissen', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts221/v4/fa/6e/5c/fa6e5caa-2d12-1d7c-a496-e26090e54366/mza_15505080922880017581.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Bayern 2 - radioWissen', url: 'https://xml.br.de/podcast/radiowissen/cast.xml', category: 'Wissen', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/1b/bf/eb/1bbfeb55-c546-d2be-a4b5-6a053cbfd5fa/mza_18029013098679093838.jpeg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Apokalypse & Filterkaffee', url: 'https://apokalypse-und-filterkaffee.podigee.io/feed/mp3', category: 'Nachrichten', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts221/v4/3b/02/55/3b0255b7-789f-2ec0-532a-d99f2dfb9f3a/mza_17192305541575822363.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Steingarts Morning Briefing', url: 'https://steingarts-morning-briefing.podigee.io/feed/mp3', category: 'Wirtschaft', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/b9/46/89/b946897a-544b-4e9a-10a4-a06476112912/mza_10637618897557523963.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Deutschlandfunk - Hintergrund', url: 'https://www.deutschlandfunk.de/podcast-hintergrund.xml', category: 'Politik', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/ab/c3/55/abc3555f-8636-f3b1-2856-f698d2ca01ae/mza_7777174620019253459.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Deutschlandfunk Nova - Eine Stunde History', url: 'https://www.deutschlandfunknova.de/podcast/eine-stunde-history', category: 'Geschichte', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/f4/e0/9b/f4e09b30-c44d-db13-6629-19ec006e0d9b/mza_11674488421865245842.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Deutschlandfunk Nova - Hörsaal', url: 'https://www.deutschlandfunknova.de/podcast/hoersaal', category: 'Wissen', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/f4/e0/9b/f4e09b30-c44d-db13-6629-19ec006e0d9b/mza_11674488421865245842.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'WDR 5 - Das philosophische Radio', url: 'https://www1.wdr.de/radio/podcasts/wdr5/philosophisches-radio-106.podcast', category: 'Kultur', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/08/cf/7a/08cf7aa1-fc4e-e1d1-678c-85e82b78ce13/mza_12702758172909403163.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'WDR 5 - Presseclub', url: 'https://www1.wdr.de/radio/podcasts/wdr5/presseclub-106.podcast', category: 'Politik', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/08/cf/7a/08cf7aa1-fc4e-e1d1-678c-85e82b78ce13/mza_12702758172909403163.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Macht & Millionen', url: 'https://machtundmillionen.podigee.io/feed/mp3', category: 'Wirtschaft', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts221/v4/b7/02/bf/b702bf92-41d6-d079-66bf-e9cefa38fb65/mza_17208846387087611311.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Kalk & Welk', url: 'https://www.radioeins.de/archiv/podcast/kalk_und_welk.xml/feed=podcast.xml', category: 'Comedy', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/45/85/80/458580f1-dafc-da38-a15d-00ff734346bb/mza_16391444175317711475.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Einschlafen Podcast', url: 'https://einschlafen-podcast.de/feed/mp3/', category: 'Unterhaltung', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts124/v4/08/67/43/086743b1-0985-1d0b-3fc0-9e66ffb2d952/mza_15509376643265213451.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Aufwachen! Podcast', url: 'https://aufwachen-podcast.de/feed/mp3/', category: 'Politik', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/ae/a8/1b/aea81bd1-31a8-9d83-4a16-ea3ea99d54e4/mza_10794539828599427027.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Methodisch inkorrekt!', url: 'https://minkorrekt.de/feed/mp3/', category: 'Wissen', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts125/v4/8f/59/70/8f5970c3-c288-c878-57d6-8488e0cb56fb/mza_12948792015093466472.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Sternengeschichten', url: 'https://sternengeschichten.podigee.io/feed/mp3', category: 'Wissen', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts125/v4/77/40/a9/7740a92f-ee83-aa9d-161e-1f879bf6bb9a/mza_5430856007412195034.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'CRE: Technik, Kultur, Gesellschaft', url: 'https://cre.fm/feed/m4a', category: 'Gesellschaft', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts115/v4/b1/70/c3/b170c3e7-38e9-4e78-0ee1-c67b66dfaa8c/mza_6436406932402128509.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Logbuch:Netzpolitik', url: 'https://logbuch-netzpolitik.de/feed/m4a', category: 'Politik', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts4/v4/73/ae/d5/73aed511-b0be-26f6-419b-c40fa9760775/mza_444908906927976210.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'WRINT: Wissenschaft', url: 'https://wrint.de/category/wissenschaft/feed/', category: 'Wissen', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts123/v4/7d/ae/61/7dae61c3-294d-9102-da76-a0e28f3cbef1/mza_15535359738096245155.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Piratensender Powerplay', url: 'https://piratensenderpowerplay.podigee.io/feed/mp3', category: 'Politik', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/b5/e7/bf/b5e7bfb1-9e7f-7bc8-038c-8f4b0051cb5a/mza_8317769913745265555.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Sicherheitshalber', url: 'https://sicherheitspod.de/feed/mp3/', category: 'Politik', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts125/v4/b8/40/6c/b8406ce9-dfdb-d8bc-7053-90d2975971db/mza_9599607834571936306.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Alles Gesagt?', url: 'https://feeds.simplecast.com/Y_bRXaw2', category: 'Interview', language: 'de', imageUrl: 'https://image.simplecastcdn.com/images/d51f2924-ec7a-47a6-bcfe-0645013e5925/e6fb673f-3a32-4077-8e4f-ddea292bc8cb/3000x3000/agcover.jpg?aid=rss_feed' },
  { type: 'podcasts', title: 'Servus. Grüezi. Hallo.', url: 'https://servus-gruezi-hallo.podigee.io/feed/mp3', category: 'Politik', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/16/8b/3c/168b3cc1-da50-a931-e408-ff61690a2a5e/mza_10693529367295240217.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Das Politikteil', url: 'https://das-politikteil.podigee.io/feed/mp3', category: 'Politik', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/70/06/86/70068695-177b-60a6-c87d-81525a4d46ad/mza_6513361132714022416.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Was jetzt?', url: 'https://feed.podbean.com/wasjetzt-diewoche/feed.xml', category: 'Nachrichten', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/ad/9f/e3/ad9fe3c0-b992-f698-75da-7c923dbc7fdb/mza_212710244437741273.png/600x600bb.jpg' },
  { type: 'podcasts', title: 'Das Podcast Ufo', url: 'https://podcast-ufo.fail/feed/mp3', category: 'Comedy', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/90/88/4f/90884f67-8f74-3ee2-b883-fa38f8cf62ec/mza_17208846387087611311.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Plauschangriff', url: 'https://plauschangriff.podigee.io/feed/mp3', category: 'Gaming', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/43/f6/ff/43f6ffbe-993d-d5a2-b91c-99d9b6264ffc/mza_16391444175317711475.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Hooked FM', url: 'https://hooked.podcaster.de/hooked.rss', category: 'Gaming', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/bf/03/49/bf0349a7-47b2-031a-07d2-004313f8d227/mza_17192305541575822363.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'The Pod / Auf ein Bier', url: 'https://www.gamespodcast.de/feed/', category: 'Gaming', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts113/v4/e6/4d/dd/e64ddd90-ee9d-bb8f-71d1-2762e638f052/mza_8854633338234475569.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Stay Forever', url: 'https://www.stayforever.de/feed/podcast/', category: 'Gaming', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts221/v4/52/d3/4c/52d34c05-f9be-cfd0-9d58-9411ca7347a5/mza_15509376643265213451.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Mordlust', url: 'https://mordlust.podigee.io/feed/mp3', category: 'True Crime', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/33/fd/32/33fd32e7-d4fa-a6be-35a1-ea5f8ef7a151/mza_10794539828599427027.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Verbrechen von nebenan', url: 'https://verbrechenvonnebenan.podigee.io/feed/mp3', category: 'True Crime', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/99/ed/ca/99edca11-d703-90d5-3977-ef56023cb603/mza_12948792015093466472.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'WDR 2 Jörg Thadeusz', url: 'https://www1.wdr.de/mediathek/audio/wdr2/wdr2-thadeusz/joerg-thadeusz-102.podcast', category: 'Interview', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/ae/4e/e4/ae4ee473-b31c-6d9b-640a-5c6218d6e355/mza_5430856007412195034.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'OMR Podcast', url: 'https://omrpodcast.podigee.io/feed/mp3', category: 'Wirtschaft', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/e1/05/26/e1052601-381c-99f6-189a-6be7a01d6364/mza_6436406932402128509.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Doppelgänger Tech Talk', url: 'https://www.doppelgaenger.io/feed/podcast', category: 'Wirtschaft', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/75/93/3f/75933fe1-3957-c584-ea17-06305a415ff6/mza_444908906927976210.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Kassenzone', url: 'https://kassenzone.podigee.io/feed/mp3', category: 'Wirtschaft', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts221/v4/ee/68/f6/ee68f619-3547-51a8-86d7-ea88085611cb/mza_15535359738096245155.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Die neuen Zwanziger', url: 'https://neuezwanziger.de/feed/mp3/', category: 'Politik', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts221/v4/18/6b/8d/186b8d96-51f1-3ec7-8321-7dae61c3294d/mza_8317769913745265555.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Die Wochendämmerung', url: 'https://wochendaemmerung.de/feed/mp3/', category: 'Nachrichten', language: 'de', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts114/v4/23/94/ea/2394eaf1-7ba8-e7c6-7f46-6fe3b09b65c9/mza_9599607834571936306.jpg/600x600bb.jpg' },

  // ==========================================
  // FEEDS (Deutsch)
  // ==========================================
  { type: 'feeds', title: 'Heise Online News', url: 'https://www.heise.de/rss/heise-atom.xml', category: 'Tech', language: 'de' },
  { type: 'feeds', title: 'Heise Developer', url: 'https://www.heise.de/developer/rss/news-atom.xml', category: 'Tech', language: 'de' },
  { type: 'feeds', title: 'Tagesschau', url: 'https://www.tagesschau.de/xml/rss2/', category: 'Nachrichten', language: 'de' },
  { type: 'feeds', title: 'Spiegel Online', url: 'https://www.spiegel.de/schlagzeilen/tops/index.rss', category: 'Nachrichten', language: 'de' },
  { type: 'feeds', title: 'Golem.de', url: 'https://rss.golem.de/rss.php?feed=RSS2.0', category: 'Tech', language: 'de' },
  { type: 'feeds', title: 'T3N News', url: 'https://t3n.de/news/feed/', category: 'Tech', language: 'de' },
  { type: 'feeds', title: 'Caschys Blog', url: 'https://stadt-bremerhaven.de/feed/', category: 'Tech', language: 'de' },
  { type: 'feeds', title: 'Mobiflip', url: 'https://www.mobiflip.de/feed/', category: 'Tech', language: 'de' },
  { type: 'feeds', title: 'Der Postillon', url: 'https://feeds.feedburner.com/blogspot/rkEL', category: 'Satire', language: 'de' },
  { type: 'feeds', title: 'FAZ.NET Aktuell', url: 'https://www.faz.net/rss/aktuell/', category: 'Nachrichten', language: 'de' },
  { type: 'feeds', title: 'SZ.de Top-Themen', url: 'https://rss.sueddeutsche.de/rss/Topthemen', category: 'Nachrichten', language: 'de' },
  { type: 'feeds', title: 'Zeit Online', url: 'https://newsfeed.zeit.de/index', category: 'Nachrichten', language: 'de' },
  { type: 'feeds', title: 'Stern.de', url: 'https://www.stern.de/feed/standard/alle-nachrichten/', category: 'Nachrichten', language: 'de' },
  { type: 'feeds', title: 'NZZ International', url: 'https://www.nzz.ch/international.rss', category: 'Nachrichten', language: 'de' },
  { type: 'feeds', title: 'SRF News', url: 'https://www.srf.ch/news/bnf/rss/1646', category: 'Nachrichten', language: 'de' },
  { type: 'feeds', title: 'Kicker Top-News', url: 'https://rss.kicker.de/news/aktuell', category: 'Sport', language: 'de' },
  { type: 'feeds', title: 'Sport1', url: 'https://www.sport1.de/news/rss', category: 'Sport', language: 'de' },
  { type: 'feeds', title: '11 FREUNDE', url: 'https://11freunde.de/feed/rss/', category: 'Sport', language: 'de' },
  { type: 'feeds', title: 'Winfuture', url: 'https://static.winfuture.de/feeds/WinFuture-News-rss2.0.xml', category: 'Tech', language: 'de' },
  { type: 'feeds', title: 'Netzpolitik.org', url: 'https://netzpolitik.org/feed/', category: 'Politik', language: 'de' },
  { type: 'feeds', title: 'Krautreporter', url: 'https://krautreporter.de/feed.rss', category: 'Journalismus', language: 'de' },
  { type: 'feeds', title: 'Bildblog', url: 'https://bildblog.de/feed/', category: 'Journalismus', language: 'de' },
  { type: 'feeds', title: 'Deskmodder', url: 'https://www.deskmodder.de/blog/feed/', category: 'Tech', language: 'de', imageUrl: 'https://www.deskmodder.de/public/logos/deskmodder_logo.png' },
  { type: 'feeds', title: 'ComputerBase', url: 'https://www.computerbase.de/rss/news.xml', category: 'Tech', language: 'de' },
  { type: 'feeds', title: 'Hardwareluxx', url: 'https://www.hardwareluxx.de/index.php?format=feed&type=rss', category: 'Tech', language: 'de' },
  { type: 'feeds', title: 'PC Games Hardware', url: 'https://www.pcgameshardware.de/feed/rss2/', category: 'Gaming', language: 'de' },
  { type: 'feeds', title: 'GameStar', url: 'https://www.gamestar.de/news/rss/news.rss', category: 'Gaming', language: 'de' },
  { type: 'feeds', title: '4Players', url: 'https://www.4players.de/feeds/news.xml', category: 'Gaming', language: 'de' },
  { type: 'feeds', title: 'Handelsblatt', url: 'https://www.handelsblatt.com/contentexport/feed/top-themen', category: 'Wirtschaft', language: 'de' },
  { type: 'feeds', title: 'WirtschaftsWoche', url: 'https://www.wiwo.de/contentexport/feed/rss/schlagzeilen', category: 'Wirtschaft', language: 'de' },
  { type: 'feeds', title: 'Tagesspiegel', url: 'https://www.tagesspiegel.de/contentexport/feed/home', category: 'Nachrichten', language: 'de' },
  { type: 'feeds', title: 'taz.de', url: 'https://taz.de/!p4608;rss/', category: 'Nachrichten', language: 'de' },
  { type: 'feeds', title: 'Focus Online', url: 'https://rss.focus.de/fol/XML/rss_folnews.xml', category: 'Nachrichten', language: 'de' },
  { type: 'feeds', title: 'Welt.de', url: 'https://www.welt.de/feeds/topnews.rss', category: 'Nachrichten', language: 'de' },
  { type: 'feeds', title: 'Der Standard', url: 'https://www.derstandard.at/rss', category: 'Nachrichten', language: 'de' },
  { type: 'feeds', title: 'Krone.at', url: 'https://www.krone.at/rss/news.xml', category: 'Nachrichten', language: 'de' },
  { type: 'feeds', title: 'Blick.ch', url: 'https://www.blick.ch/news/rss.xml', category: 'Nachrichten', language: 'de' },
  { type: 'feeds', title: '20 Minuten', url: 'https://www.20min.ch/rss/front', category: 'Nachrichten', language: 'de' },

  // ==========================================
  // RADIO (International & Deutsch)
  // ==========================================
  { type: 'radio', title: 'WDR 1LIVE', url: 'https://wdr-1live-live.icecast.wdr.de/wdr/1live/live/mp3/128/stream.mp3', category: 'Pop', language: 'de' },
  { type: 'radio', title: 'WDR 2', url: 'https://wdr-wdr2-rheinruhr.icecast.wdr.de/wdr/wdr2/rheinruhr/mp3/128/stream.mp3', category: 'Pop', language: 'de' },
  { type: 'radio', title: 'WDR 3', url: 'https://wdr-wdr3-live.icecast.wdr.de/wdr/wdr3/live/mp3/128/stream.mp3', category: 'Kultur', language: 'de' },
  { type: 'radio', title: 'WDR 4', url: 'https://wdr-wdr4-live.icecast.wdr.de/wdr/wdr4/live/mp3/128/stream.mp3', category: 'Oldies', language: 'de' },
  { type: 'radio', title: 'WDR 5', url: 'https://wdr-wdr5-live.icecast.wdr.de/wdr/wdr5/live/mp3/128/stream.mp3', category: 'Wort', language: 'de' },
  { type: 'radio', title: 'COSMO', url: 'https://wdr-cosmo-live.icecast.wdr.de/wdr/cosmo/live/mp3/128/stream.mp3', category: 'Pop', language: 'de' },
  { type: 'radio', title: 'SWR1 BW', url: 'https://swr-swr1-bw.cast.addradio.de/swr/swr1/bw/mp3/128/stream.mp3', category: 'Pop', language: 'de' },
  { type: 'radio', title: 'SWR2', url: 'https://swr-swr2-live.cast.addradio.de/swr/swr2/live/mp3/128/stream.mp3', category: 'Kultur', language: 'de' },
  { type: 'radio', title: 'SWR3', url: 'https://swr-swr3-live.cast.addradio.de/swr/swr3/live/mp3/128/stream.mp3', category: 'Pop', language: 'de' },
  { type: 'radio', title: 'SWR4 BW', url: 'https://swr-swr4-bw.cast.addradio.de/swr/swr4/bw/mp3/128/stream.mp3', category: 'Schlager', language: 'de' },
  { type: 'radio', title: 'DASDING', url: 'https://swr-dasding-live.cast.addradio.de/swr/dasding/live/mp3/128/stream.mp3', category: 'Pop', language: 'de' },
  { type: 'radio', title: 'NDR 1 Niedersachsen', url: 'https://ndr-ndr1niedersachsen-hannover.cast.addradio.de/ndr/ndr1niedersachsen/hannover/mp3/128/stream.mp3', category: 'Pop', language: 'de' },
  { type: 'radio', title: 'NDR 2', url: 'https://ndr-ndr2-niedersachsen.cast.addradio.de/ndr/ndr2/niedersachsen/mp3/128/stream.mp3', category: 'Pop', language: 'de' },
  { type: 'radio', title: 'N-JOY', url: 'https://ndr-njoy-live.cast.addradio.de/ndr/njoy/live/mp3/128/stream.mp3', category: 'Pop', language: 'de' },
  { type: 'radio', title: 'NDR Info', url: 'https://ndr-ndrinfo-live.cast.addradio.de/ndr/ndrinfo/live/mp3/128/stream.mp3', category: 'Nachrichten', language: 'de' },
  { type: 'radio', title: 'BR-Klassik', url: 'https://br-brklassik-live.cast.addradio.de/br/brklassik/live/mp3/128/stream.mp3', category: 'Klassik', language: 'de' },
  { type: 'radio', title: 'Bayern 1', url: 'https://br-bayern1-obb.cast.addradio.de/br/bayern1/obb/mp3/128/stream.mp3', category: 'Pop', language: 'de' },
  { type: 'radio', title: 'Bayern 2', url: 'https://br-bayern2-sued.cast.addradio.de/br/bayern2/sued/mp3/128/stream.mp3', category: 'Kultur', language: 'de' },
  { type: 'radio', title: 'Bayern 3', url: 'https://br-bayern3-live.cast.addradio.de/br/bayern3/live/mp3/128/stream.mp3', category: 'Pop', language: 'de' },
  { type: 'radio', title: 'BR24', url: 'https://br-br24-live.cast.addradio.de/br/br24/live/mp3/128/stream.mp3', category: 'Nachrichten', language: 'de' },
  { type: 'radio', title: 'Antenne Bayern', url: 'https://mp3channels.webradio.antenne.de/antenne', category: 'Pop', language: 'de' },
  { type: 'radio', title: 'Rock Antenne', url: 'https://mp3channels.webradio.antenne.de/rockantenne', category: 'Rock', language: 'de' },
  { type: 'radio', title: 'Radio BOB!', url: 'https://bob.hoerradar.de/radiobob-live-mp3-hq', category: 'Rock', language: 'de' },
  { type: 'radio', title: 'sunshine live', url: 'https://sunshinelive.hoerradar.de/sunshinelive-live-mp3-hq', category: 'Electronic', language: 'de' },
  { type: 'radio', title: 'bigFM', url: 'https://streams.bigfm.de/bigfm-deutschland-128-mp3', category: 'Urban', language: 'de' },
  { type: 'radio', title: 'BBC Radio 1', url: 'http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one', category: 'Pop', language: 'en' },
  { type: 'radio', title: 'BBC Radio 2', url: 'http://stream.live.vc.bbcmedia.co.uk/bbc_radio_two', category: 'Pop', language: 'en' },
  { type: 'radio', title: 'BBC Radio 3', url: 'http://stream.live.vc.bbcmedia.co.uk/bbc_radio_three', category: 'Klassik', language: 'en' },
  { type: 'radio', title: 'BBC Radio 4', url: 'http://stream.live.vc.bbcmedia.co.uk/bbc_radio_fourfm', category: 'Wort', language: 'en' },
  { type: 'radio', title: 'BBC Radio 6 Music', url: 'http://stream.live.vc.bbcmedia.co.uk/bbc_6music', category: 'Alternative', language: 'en' },
  { type: 'radio', title: 'Radio Swiss Pop', url: 'http://stream.srg-ssr.ch/m/rsp/mp3_128', category: 'Pop', language: 'de' },
  { type: 'radio', title: 'Radio Swiss Jazz', url: 'http://stream.srg-ssr.ch/m/rsj/mp3_128', category: 'Jazz', language: 'de' },
  { type: 'radio', title: 'Radio Swiss Classic', url: 'http://stream.srg-ssr.ch/m/rsc_de/mp3_128', category: 'Klassik', language: 'de' },
  { type: 'radio', title: 'Wacken Radio', url: 'https://wacken.stream.laut.fm/wacken', category: 'Heavy Metal', language: 'de' },
  { type: 'radio', title: '100% 80er', url: 'https://mp3channels.webradio.antenne.de/80er-hits', category: '80s', language: 'de' },
  { type: 'radio', title: '100% 90er', url: 'https://mp3channels.webradio.antenne.de/90er-hits', category: '90s', language: 'de' },
  { type: 'radio', title: 'Defjay', url: 'https://defjay.stream.laut.fm/defjay', category: 'Black', language: 'de' },
  { type: 'radio', title: 'KEXP', url: 'https://kexp-mp3-128.streamguys1.com/kexp128.mp3', category: 'Alternative', language: 'en' },
  { type: 'radio', title: 'NTS Radio 1', url: 'https://stream-relay-geo.ntslive.net/stream', category: 'Alternative', language: 'en' },
  { type: 'radio', title: 'NTS Radio 2', url: 'https://stream-relay-geo.ntslive.net/stream2', category: 'Alternative', language: 'en' },
  { type: 'radio', title: 'SomaFM: Groove Salad', url: 'https://ice1.somafm.com/groovesalad-128-mp3', category: 'Chillout', language: 'en' },
  { type: 'radio', title: 'SomaFM: Drone Zone', url: 'https://ice1.somafm.com/dronezone-128-mp3', category: 'Ambient', language: 'en' },
  { type: 'radio', title: 'SomaFM: Secret Agent', url: 'https://ice1.somafm.com/secretagent-128-mp3', category: 'Chillout', language: 'en' },
  
  // ==========================================
  // YOUTUBE (International & Deutsch)
  // ==========================================
  { type: 'youtube', title: 'Kurzgesagt - In a Nutshell', url: 'https://www.youtube.com/@kurzgesagt', category: 'Wissen', language: 'de' },
  { type: 'youtube', title: 'Dinge Erklärt – Kurzgesagt', url: 'https://www.youtube.com/@kurzgesagt_de', category: 'Wissen', language: 'de' },
  { type: 'youtube', title: 'MKBHD', url: 'https://www.youtube.com/@mkbhd', category: 'Tech', language: 'en' },
  { type: 'youtube', title: 'Veritasium', url: 'https://www.youtube.com/@veritasium', category: 'Wissen', language: 'en' },
  { type: 'youtube', title: 'Linus Tech Tips', url: 'https://www.youtube.com/@LinusTechTips', category: 'Tech', language: 'en' },
  { type: 'youtube', title: 'ARTEde', url: 'https://www.youtube.com/@ARTEde', category: 'Doku', language: 'de' },
  { type: 'youtube', title: 'ZDFheute Nachrichten', url: 'https://www.youtube.com/@ZDFheute', category: 'Nachrichten', language: 'de' },
  { type: 'youtube', title: 'PietSmiet', url: 'https://www.youtube.com/@PietSmiet', category: 'Gaming', language: 'de' },
  { type: 'youtube', title: 'Gronkh', url: 'https://www.youtube.com/@gronkh', category: 'Gaming', language: 'de' },
  { type: 'youtube', title: 'MrBeast', url: 'https://www.youtube.com/@MrBeast', category: 'Unterhaltung', language: 'en' },
  { type: 'youtube', title: 'PewDiePie', url: 'https://www.youtube.com/@PewDiePie', category: 'Gaming', language: 'en' },
  { type: 'youtube', title: 'Markiplier', url: 'https://www.youtube.com/@markiplier', category: 'Gaming', language: 'en' },
  { type: 'youtube', title: 'Jacksepticeye', url: 'https://www.youtube.com/@jacksepticeye', category: 'Gaming', language: 'en' },
  { type: 'youtube', title: 'Y-Kollektiv', url: 'https://www.youtube.com/@ykollektiv', category: 'Doku', language: 'de' },
  { type: 'youtube', title: 'STRG_F', url: 'https://www.youtube.com/@STRG_F', category: 'Doku', language: 'de' },
  { type: 'youtube', title: 'Simplicissimus', url: 'https://www.youtube.com/@Simplicissimus', category: 'Wissen', language: 'de' },
  { type: 'youtube', title: 'mailab', url: 'https://www.youtube.com/@maiLab', category: 'Wissen', language: 'de' },
  { type: 'youtube', title: 'Leeroy will\'s wissen!', url: 'https://www.youtube.com/@Leeroymatata', category: 'Interview', language: 'de' },
  { type: 'youtube', title: 'Rezo', url: 'https://www.youtube.com/@Rezo', category: 'Unterhaltung', language: 'de' },
  { type: 'youtube', title: 'Julien Bam', url: 'https://www.youtube.com/@JulienBam', category: 'Unterhaltung', language: 'de' },
  { type: 'youtube', title: 'Dhalucard', url: 'https://www.youtube.com/@dhalucard', category: 'Gaming', language: 'de' },
  { type: 'youtube', title: 'IGN', url: 'https://www.youtube.com/@IGN', category: 'Gaming', language: 'en' },
  { type: 'youtube', title: 'GameSpot', url: 'https://www.youtube.com/@gamespot', category: 'Gaming', language: 'en' },
  { type: 'youtube', title: 'Digital Foundry', url: 'https://www.youtube.com/@DigitalFoundry', category: 'Gaming', language: 'en' },
  { type: 'youtube', title: 'Tom Scott', url: 'https://www.youtube.com/@TomScottGo', category: 'Wissen', language: 'en' },
  { type: 'youtube', title: 'SmarterEveryDay', url: 'https://www.youtube.com/@smartereveryday', category: 'Wissen', language: 'en' },
  { type: 'youtube', title: 'Cleo Abram', url: 'https://www.youtube.com/@CleoAbram', category: 'Wissen', language: 'en' },
  { type: 'youtube', title: 'Hardware Unboxed', url: 'https://www.youtube.com/@Hardwareunboxed', category: 'Tech', language: 'en' },
  { type: 'youtube', title: 'Gamers Nexus', url: 'https://www.youtube.com/@GamersNexus', category: 'Tech', language: 'en' },

  // ==========================================
  // WEBCAMS
  // ==========================================
  { type: 'webcams', title: 'Times Square Live', url: 'https://www.youtube.com/watch?v=rnXIjl_Rzy4', category: 'City', language: 'en' },
  { type: 'webcams', title: 'ISS Live HD', url: 'https://www.youtube.com/watch?v=fO9e9jnhYK8', category: 'Space', language: 'en' },
  { type: 'webcams', title: 'Jackson Hole Town Square', url: 'https://www.youtube.com/watch?v=1EiC9bvVGnk', category: 'City', language: 'en' },
  { type: 'webcams', title: 'African Waterhole', url: 'https://www.youtube.com/watch?v=QyOitP-wXfE', category: 'Nature', language: 'en' },
  { type: 'webcams', title: 'Venice Beach Live', url: 'https://www.youtube.com/watch?v=EO_1LWqsCNE', category: 'City', language: 'en' },
  { type: 'webcams', title: 'Shibuya Crossing', url: 'https://www.youtube.com/watch?v=dfVK7ld38Ys', category: 'City', language: 'en' },
  { type: 'webcams', title: 'Kitten Academy Live', url: 'https://www.youtube.com/watch?v=t-XmGEa-Bqk', category: 'Nature', language: 'en' },
  { type: 'webcams', title: 'Monterey Bay Aquarium', url: 'https://www.youtube.com/watch?v=abbR-Ttd-cA', category: 'Nature', language: 'en' },
  { type: 'webcams', title: 'Grizzly Bears Catching Salmon', url: 'https://www.youtube.com/watch?v=pZMdje7kCWc', category: 'Nature', language: 'en' },
  { type: 'webcams', title: 'Live Surf Cam Pipeline', url: 'https://www.youtube.com/watch?v=B6qPml6o37M', category: 'Nature', language: 'en' },
  { type: 'webcams', title: 'Earth from Space (NASA)', url: 'https://www.youtube.com/watch?v=vytmBNhc9ig', category: 'Space', language: 'en' },
  { type: 'webcams', title: 'Tokyo Shinjuku Live', url: 'https://www.youtube.com/watch?v=GLQhbRGv5qU', category: 'City', language: 'en' },
  { type: 'webcams', title: 'Live from Miami Beach', url: 'https://www.youtube.com/watch?v=gT8B2h_bMxs', category: 'City', language: 'en' },
  { type: 'webcams', title: 'Las Vegas Strip Live', url: 'https://www.youtube.com/watch?v=NnOtwzHw360', category: 'City', language: 'en' },
  { type: 'webcams', title: 'Port of Hamburg', url: 'https://www.youtube.com/watch?v=OmyDLXvaus4', category: 'City', language: 'en' },
  { type: 'webcams', title: 'African Safari', url: 'https://www.youtube.com/watch?v=ydYDqZQpim8', category: 'Nature', language: 'en' },
  { type: 'webcams', title: 'Fuji-Q Highland Live', url: 'https://www.youtube.com/watch?v=vmNAFPfMK7A', category: 'Theme Park', language: 'en' },
  { type: 'webcams', title: 'Panda Cam', url: 'https://www.youtube.com/watch?v=SUXPnIEpbn4', category: 'Nature', language: 'en' },
  { type: 'webcams', title: 'Earth Cam: Key West', url: 'https://www.youtube.com/watch?v=Y5ypYTZs-7o', category: 'Beach', language: 'en' },
  
  // ==========================================
  // SPANISH SOURCES (feeds, podcasts, youtube)
  // ==========================================
  { type: 'feeds', title: 'El País', url: 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada', category: 'Nachrichten', language: 'es' },
  { type: 'feeds', title: 'El Mundo', url: 'https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml', category: 'Nachrichten', language: 'es' },
  { type: 'feeds', title: 'RTVE Noticias', url: 'https://www.rtve.es/api/noticias/rss', category: 'Nachrichten', language: 'es' },
  { type: 'feeds', title: 'Xataka', url: 'https://feeds.weblogssl.com/xataka2', category: 'Tech', language: 'es' },
  { type: 'feeds', title: 'Marca', url: 'https://e00-marca.uecdn.es/rss/portada.xml', category: 'Sport', language: 'es' },
  { type: 'podcasts', title: 'Radio Ambulante (NPR)', url: 'https://feeds.npr.org/510317/podcast.xml', category: 'Kultur', language: 'es', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/6c/cb/fe/6ccbfe05-15a4-9721-a400-f9becfd09d58/mza_10693529367295240217.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Entiende tu mente', url: 'https://entiendetumente.info/feed/podcast', category: 'Wissen', language: 'es', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/c4/e0/b4/c4e0b44b-4e9a-10a4-a064-76112912a789/mza_6513361132714022416.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Cienciaes', url: 'https://cienciaes.com/feed/', category: 'Wissen', language: 'es' },
  { type: 'podcasts', title: 'La Escóbula de la Brújula', url: 'https://www.laescobula.com/feed/', category: 'Kultur', language: 'es', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts221/v4/20/49/c1/2049c155-d603-90d5-3977-ef56023cb603/mza_17208846387087611311.jpg/600x600bb.jpg' },
  { type: 'youtube', title: 'El Rubius', url: 'https://www.youtube.com/@elrubius', category: 'Gaming', language: 'es' },
  { type: 'youtube', title: 'Ibai', url: 'https://www.youtube.com/@Ibai_Llanos', category: 'Unterhaltung', language: 'es' },
  { type: 'youtube', title: 'Quantum Fracture', url: 'https://www.youtube.com/@QuantumFracture', category: 'Wissen', language: 'es' },
  { type: 'youtube', title: 'RTVE Noticias', url: 'https://www.youtube.com/@rtve', category: 'Nachrichten', language: 'es' },

  // ==========================================
  // FRENCH SOURCES (feeds, podcasts, youtube)
  // ==========================================
  { type: 'feeds', title: 'Le Monde', url: 'https://www.lemonde.fr/rss/une.xml', category: 'Nachrichten', language: 'fr' },
  { type: 'feeds', title: 'Le Figaro', url: 'https://lefigaro.fr/rss/figaro_actualites.xml', category: 'Nachrichten', language: 'fr' },
  { type: 'feeds', title: 'Frandroid', url: 'https://www.frandroid.com/feed', category: 'Tech', language: 'fr' },
  { type: 'feeds', title: 'L\'Équipe', url: 'https://xml.lequipe.fr/Syndication/rss_Equipe_Une.xml', category: 'Sport', language: 'fr' },
  { type: 'feeds', title: 'Les Echos', url: 'https://www.lesechos.fr/rss/rss_france.xml', category: 'Wirtschaft', language: 'fr' },
  { type: 'podcasts', title: 'Choses à Savoir', url: 'https://rss.art19.com/choses-a-savoir', category: 'Wissen', language: 'fr', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts221/v4/31/55/a8/3155a8f1-dafc-da38-a15d-00ff734346bb/mza_16391444175317711475.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'Transfert (Slate.fr)', url: 'https://feed.audiomeans.fr/feed/7a42bbca-7c80-40e4-bb20-b6fef18f70fa.xml', category: 'Kultur', language: 'fr', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/3a/34/1f/3a341f67-8f74-3ee2-b883-fa38f8cf62ec/mza_17192305541575822363.jpg/600x600bb.jpg' },
  { type: 'podcasts', title: 'La Story (Les Echos)', url: 'https://rss.art19.com/la-story', category: 'Wirtschaft', language: 'fr', imageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/17/d2/2b/17d22b7f-f543-0247-5b69-2413a9428706/mza_17392971206644611221.jpg/600x600bb.jpg' },
  { type: 'youtube', title: 'Squeezie', url: 'https://www.youtube.com/@Squeezie', category: 'Unterhaltung', language: 'fr' },
  { type: 'youtube', title: 'Cyprien', url: 'https://www.youtube.com/@cyprien', category: 'Comedy', language: 'fr' },
  { type: 'youtube', title: 'HugoDécrypte', url: 'https://www.youtube.com/@HugoDecrypte', category: 'Nachrichten', language: 'fr' },
  { type: 'youtube', title: 'Nota Bene', url: 'https://www.youtube.com/@NotaBeneHistoire', category: 'Geschichte', language: 'fr' }
];
